"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { api } from "@/lib/api/client";
import type { Region } from "@/lib/api/types";
import { credits, disclaimer } from "@/lib/credits";
import { developer } from "@/lib/developer";
import { coverageSentence } from "./Coverage";
import styles from "./about.module.css";

const REAL_VS_GENERATED: { item: string; real: boolean; note: string }[] = [
  { item: "Shape of the ground (hills, crater bowls, slopes)", real: true, note: "Measured by NASA's laser altimeter, one height every 80 m." },
  { item: "Where craters, mountains and cold traps are, and their names", real: true, note: "From NASA/USGS catalogues and the IAU's official names." },
  { item: "Which places are in permanent shadow, and how sunny each spot is", real: true, note: "Computed by NASA from the same height map." },
  { item: "Ground colour and surface texture", real: false, note: "Generated by the game. We do not use real photographs, so the grey tone and grain are an artist's impression." },
  { item: "Small bumps and pebbles near the rover", real: false, note: "Generated detail, visual only. The real data is too coarse (80 m) to show them." },
  { item: "The stars", real: false, note: "Randomly placed dots. They are not the real constellations." },
  { item: "The Sun's position in the sky", real: false, note: "Kept just above the horizon, as it is near the pole, but its movement is a sped-up animation (one lap per 15 minutes instead of 29.5 days)." },
  { item: "Rover speed, steering and the auto-driver", real: false, note: "Game physics. Real rovers move at centimetres per second; ours drives at 10 to 300 m/s (60 by default, you choose)." },
  { item: "Route planning", real: true, note: "A real algorithm on real slopes, but the rover's slope limit is our assumption." },
];

/** The website's About page: what the project is, what is real, where the data comes from, and who built it. */
export function AboutPanel() {
  const [region, setRegion] = useState<Region | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    api.region().then(setRegion).catch((e) => setError(e.message));
  }, []);

  return (
    <main className={styles.page}>
      <nav className={styles.nav}>
        <Link className={styles.back} href="/">← Back to the game</Link>
      </nav>

      <h1>Lunar Rover</h1>
      <p className={styles.lead}>
        A driving game set on the <b>real lunar south pole</b>. The ground is shaped from actual NASA measurements, and a
        phone-style GPS lists real craters, sunlit ridges and shadowed places where water ice may survive. Drive up to a
        pole marked <b>i</b> to learn what that place is and why it matters.
      </p>

      <section className={styles.disclaimer}>
        <h2>How much of the Moon is covered?</h2>
        {region ? (
          <p>
            Only <b>{coverageSentence(region)}</b>: the area around the Moon&apos;s south pole, south of roughly 80°S.
            The rest of the Moon is <b>not</b> in this game, and you cannot drive out of this area.
          </p>
        ) : (
          <p>{error ?? "Loading…"}</p>
        )}
      </section>

      <section>
        <h2>How to read the GPS</h2>
        <ul>
          <li><b>Coloured dots</b> are places you can visit: blue = water &amp; ice sites, orange = craters, yellow = sunny spots, purple = mountains and landmarks. Tap one for details and a guided route.</li>
          <li><b>Green arrow</b> is your rover. Drag the map to look around, and use the ◎ button to re-centre.</li>
        </ul>
      </section>

      <section>
        <h2>Shadow and Sun: real NASA data</h2>
        <p>
          The <b>Shadow</b> and <b>Sun</b> buttons on the phone map show two real NASA maps, not game effects. Both were computed by NASA
          scientists from the Moon&apos;s measured terrain (LOLA laser altimeter) and the Sun&apos;s motion over several years, so they
          describe long-term averages, not what the Sun is doing right now.
        </p>
        <ul>
          <li>
            <b>Shadow</b> (blue) marks <i>permanently shadowed regions</i>: places where, because of the terrain and the Moon&apos;s almost-upright
            spin, the Sun never rises above the local horizon. They stay extremely cold, which is why water ice could survive there. Source: NASA GSFC
            &quot;LOLA permanently shadowed regions&quot; (Mazarico et al. 2011). Inside the game these are the dark crater floors where your headlamps switch on.
          </li>
          <li>
            <b>Sun</b> (yellow) shows <i>average solar visibility</i>: the share of time the Sun is at least partly above the horizon at each spot.
            The brighter the yellow, the more sunshine, which makes a place good for solar-powered rovers and bases. Source: NASA GSFC &quot;LOLA average
            solar visibility&quot; (Mazarico et al. 2011). It also feeds the &quot;Avg. sunlight (real)&quot; number in the telemetry.
          </li>
          <li>
            What is <b>not</b> real: the Sun you see moving in the 3D sky is a sped-up animation, and it does not follow these maps.
          </li>
        </ul>
      </section>

      <section>
        <h2>Real or made up?</h2>
        <ul className={styles.realList}>
          {REAL_VS_GENERATED.map((r) => (
            <li key={r.item}>
              <span className={r.real ? styles.real : styles.fake}>{r.real ? "Real data" : "Generated"}</span>
              <b>{r.item}</b>
              <small>{r.note}</small>
            </li>
          ))}
        </ul>
      </section>

      <section>
        <h2>The data behind it</h2>
        {error && <p>The data server is not reachable, so the dataset list cannot be shown ({error}).</p>}
        {region?.datasets.map((d) => (
          <div className={styles.dataset} key={d.id}>
            <h3>{d.title}</h3>
            <p>{d.plain}</p>
            <dl>
              <dt>Published by</dt><dd>{d.provider}</dd>
              <dt>When / who</dt><dd>{d.published}</dd>
              <dt>Reference</dt><dd>{d.citation}</dd>
              <dt>Used here for</dt><dd>{d.used_for}</dd>
            </dl>
            <a href={d.url} target="_blank" rel="noreferrer">Source ↗</a>
          </div>
        ))}
        {region?.extra_credits.map((d) => (
          <div className={styles.dataset} key={d.title}>
            <h3>{d.title}</h3>
            <p>{d.plain}</p>
            <dl>
              <dt>Published</dt><dd>{d.published}</dd>
              <dt>Used here for</dt><dd>{d.used_for}</dd>
            </dl>
          </div>
        ))}
      </section>

      <section>
        <h2>What the project does with the data</h2>
        <ol>
          <li>A processing script downloads the NASA files and lines them all up on one map.</li>
          <li>It cuts the height map into tiles at several levels of detail, and measures things such as crater depth and how much of each crater floor is in shadow.</li>
          <li>A server answers questions: what is near me, what is at this spot, what is the easiest route between two places.</li>
          <li>The game draws the terrain in 3D from those tiles and shows the GPS and the information cards.</li>
        </ol>
      </section>

      <section>
        <h2>Why is it useful?</h2>
        <ul>
          <li><b>Education:</b> a hands-on way to see why the south pole matters - permanent shadows may hold water ice, and nearby ridges get lots of sunlight for power.</li>
          <li><b>Mission thinking:</b> it shows how planners weigh slope, sunlight and distance when choosing where a rover should go.</li>
          <li><b>Open data demo:</b> everything comes from public datasets, so the same approach can be extended to other regions as more data is added.</li>
        </ul>
        <p className={styles.limits}>
          It is <b>not</b> a mission-planning tool: the terrain is 80 m resolution, ice at the shadowed sites is only a
          possibility (only the LCROSS site is confirmed), and rover behaviour is simplified.
        </p>
      </section>

      <section>
        <h2>Credits</h2>
        <ul className={styles.credits}>
          {credits.map((c) => (
            <li key={c.name}>
              <b>{c.url ? <a href={c.url} target="_blank" rel="noreferrer">{c.name}</a> : c.name}</b> - {c.what} <small>({c.licence})</small>
            </li>
          ))}
        </ul>
        <p className={styles.limits}>{disclaimer}</p>
      </section>

      <section className={styles.developer}>
        <h2>About the developer</h2>
        <p><b>{developer.name}</b> ({developer.handle})</p>
        <p>{developer.intro}</p>
        <p>
          {developer.links.map((l) => (
            <a key={l.url} href={l.url} target="_blank" rel="noreferrer">{l.label} ↗</a>
          ))}
        </p>
      </section>
    </main>
  );
}
